//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace neveinNadeen.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IMDb_Entities : DbContext
    {
        public IMDb_Entities()
            : base("name=IMDb_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActorMovies> ActorMovies { get; set; }
        public virtual DbSet<Actors> Actors { get; set; }
        public virtual DbSet<Comments> Comments { get; set; }
        public virtual DbSet<Directors> Directors { get; set; }
        public virtual DbSet<FavActors> FavActors { get; set; }
        public virtual DbSet<FavDirectors> FavDirectors { get; set; }
        public virtual DbSet<FavMovies> FavMovies { get; set; }
        public virtual DbSet<IMDb_User> IMDb_User { get; set; }
        public virtual DbSet<Movies> Movies { get; set; }
        public virtual DbSet<Rates> Rates { get; set; }
    }
}
